# Generated by Django 3.0.8 on 2020-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200811_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
